openapi: 3.0.3
info:
  title: API Specification for Issue-Service
  description: API Specification for Gateway-Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8069'
paths:
  /api/projects:
    get:
      description: |
        Get all Projects for this User
      responses:
        '200':
          description: List of available Projects
          content:
            application/json:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string
    post:
      description: |
        Create a new Project
      requestBody:
        description: projectDTO
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
      responses:
        '201':
          description: Created Project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '409':
          description: Project creator does not exist
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string

  /api/projects/{projectId}:
    get:
      description: Get a project by projectid
      responses:
        '200':
          description: Project
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: projectId
          in: path
          description: ID of project
          required: true
          schema:
            type: string
            format: uuid
            example: 'e42e93d1-56dc-4687-9039-beb25dc1732a'

    delete:
      description: Delete Project
      responses:
        '200':
          description: Project
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: projectId
          in: path
          description: ID of project
          required: true
          schema:
            type: string
            format: uuid
            example: 'e42e93d1-56dc-4687-9039-beb25dc1732a'

  /api/projects/users/{userId}:
    get:
      description: Get projects of the given user
      responses:
        '200':
          description: Project
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
            format: uuid
            example: '8d8fa2d7-b999-4e07-9739-c563ee9fb12b'

  /api/projects/{uuid}/members:
    get:
      description: Get project of the given id
      responses:
        '200':
          description: Project
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: uuid
          in: path
          description: ID of project
          required: true
          schema:
            type: string
            format: uuid
            example: 'e86c57cb-d703-4f39-9632-3782cb5500e8'

components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        creatorId:
          type: string
          format: uuid
        createTime:
          type: string
          format: date-time

    ArrayOfProjects:
      type: array
      items:
        $ref: '#/components/schemas/Project'

    ProjectDTO:
      type: object
      required:
        - name
        - members
      properties:
        name:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/MemberDTO'

    MemberDTO:
      type: object
      required:
        - userId
        - projectRole
      properties:
        userId:
          type: string
          format: uuid
          example: "8d8fa2d7-b999-4e07-9739-c563ee9fb12b"
        projectRole:
          type: string
          example: "boss"
